// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeVoice.Data;

#nullable disable

namespace SafeVoice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403104028_AddSupportLocations")]
    partial class AddSupportLocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("SafeVoice.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateResolved")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateReviewed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHighPriority")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("ModeratorNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipToVictim")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReporterContact")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReporterName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportingAs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresGardaAttention")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubmittedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VictimAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VictimName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("SubmittedByUserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("SafeVoice.Models.SupportLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Is24Hour")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmergency")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Services")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SupportLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Park Street, Dundalk, Co. Louth",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Louth",
                            Is24Hour = true,
                            IsActive = true,
                            IsEmergency = true,
                            Latitude = 53.999400000000001,
                            Longitude = -6.4019000000000004,
                            Name = "Dundalk Garda Station",
                            OpeningHours = "24/7",
                            Phone = "042-9388400",
                            StationCode = "DUN",
                            Type = "GardaStation"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Crowe Street, Dundalk, Co. Louth",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Child and Family Agency services",
                            Email = "dundalk@tusla.ie",
                            Is24Hour = false,
                            IsActive = true,
                            IsEmergency = false,
                            Latitude = 54.001399999999997,
                            Longitude = -6.4050000000000002,
                            Name = "Tusla Dundalk",
                            OpeningHours = "Mon-Fri 9:00-17:00",
                            Phone = "042-9394700",
                            Services = "Child protection, family support, welfare services",
                            Type = "Tusla"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Stapleton Place, Dundalk, Co. Louth",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Health and social care services",
                            Is24Hour = false,
                            IsActive = true,
                            IsEmergency = false,
                            Latitude = 54.004100000000001,
                            Longitude = -6.3981000000000003,
                            Name = "HSE Louth Community Services",
                            OpeningHours = "Mon-Fri 9:00-17:00",
                            Phone = "041-6850000",
                            Services = "Mental health, community care, counselling",
                            Type = "HSE"
                        },
                        new
                        {
                            Id = 4,
                            Address = "National Service",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Free 24/7 listening service for children",
                            Is24Hour = true,
                            IsActive = true,
                            IsEmergency = false,
                            Latitude = 53.349800000000002,
                            Longitude = -6.2603,
                            Name = "Childline",
                            OpeningHours = "24/7",
                            Phone = "1800-666666",
                            Services = "Confidential support for children and young people",
                            Type = "Helpline",
                            Website = "https://childline.ie"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Drogheda, Co. Louth",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Emergency medical services",
                            Is24Hour = true,
                            IsActive = true,
                            IsEmergency = true,
                            Latitude = 53.717500000000001,
                            Longitude = -6.3476999999999997,
                            Name = "Our Lady of Lourdes Hospital",
                            OpeningHours = "24/7 Emergency",
                            Phone = "041-9874000",
                            Services = "Emergency department, paediatric care",
                            Type = "Hospital"
                        });
                });

            modelBuilder.Entity("SafeVoice.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BadgeNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SafeVoice.Models.Report", b =>
                {
                    b.HasOne("SafeVoice.Models.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SafeVoice.Models.User", "SubmittedByUser")
                        .WithMany("Reports")
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReviewedByUser");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("SafeVoice.Models.User", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
